site:
  title: Apicurio Registry
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://www.apicur.io/registry/docs
  start_page: apicurio-registry::index.adoc
content:
  sources:
  - url: https://github.com/Apicurio/apicurio-registry.git
    branches: master
    start_path: docs
    edit_url: '{web_url}'

ui:
  bundle:
    url: https://raw.githubusercontent.com/Apicurio/apicurio-docs-ui/master/dist/ui-bundle.zip
    snapshot: true
  output_dir: assets

runtime:
  cache_dir: ./target/antora-cache

output:
  dir: ./target/dist

asciidoc:
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true
    mod-loc: partial$
    registry-overview: link:assembly-intro-to-the-registry.html[Registry Overview]
    registry-rules: link:assembly-intro-to-registry-rules.html[Introduction to Apicurio Registry rules]
    registry-artifact-types: link:assembly-registry-reference.html[Apicurio Registry reference] 
    registry-rule-types: link:assembly-registry-reference.html[Apicurio Registry reference]
    managing-registry-artifacts-ui: link:assembly-managing-registry-artifacts-ui.html[Managing Apicurio Registry content using the web console]
    installing-the-registry-docker: link:assembly-installing-the-registry-docker.html[Installing Apicurio Registry using Docker]
    installing-the-registry-openshift: link:assembly-installing-the-registry-openshift.html[Installing Apicurio Registry on OpenShift]
